version: '3'

services:
  app:
    build: .
    ports:
      - "8100:8000"
    environment:
      PORT: 8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: my_database
      DB_USERNAME: my_user
      DB_PASSWORD: my_password
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
